services:
  backend:
   image: zono32/examen-back:latest
   container_name: examen-back
   ports:
     - 8001:8001

  frontend:
   image: zono32/examen-front:latest
   container_name: examen-front
   depends_on: 
    - backend
   ports:
    - 80:80